"""Write results tables into a README and verify them against saved runs."""

from __future__ import annotations

import math
import os
import re
from dataclasses import dataclass, field
from pathlib import Path

from .store import SavedRun, is_run_dir

START = "<!-- results:start -->"
END = "<!-- results:end -->"
MISSING = "—"


def format_value(value, precision: int | None) -> str:
    if value is None:
        return MISSING
    if isinstance(value, bool) or isinstance(value, int):
        return str(int(value))
    if isinstance(value, float):
        if precision is None or not math.isfinite(value):
            return repr(value)
        if value != 0 and abs(value) < 0.5 * 10**-precision:  # would print as 0.000
            return f"{value:.{max(precision - 1, 1)}e}"
        return f"{value:.{precision}f}"
    return str(value).replace("|", "\\|")


def _github_url(remote: str | None) -> str | None:
    if not remote:
        return None
    m = re.match(r"(?:https?://|git@)(github\.com|gitlab\.com)[/:](.+?)(?:\.git)?/?$", remote)
    return f"https://{m.group(1)}/{m.group(2)}" if m else None


def commit_cell(run: SavedRun) -> str:
    git = run.meta.get("git", {})
    commit = git.get("commit")
    if not commit:
        return "no-git"
    label = f"`{commit[:7]}`"
    base = _github_url(git.get("remote"))
    cell = f"[{label}]({base}/commit/{commit})" if base else label
    return cell + (" (dirty)" if git.get("dirty") else "")


def render_table(
    runs: list[SavedRun],
    metrics: list[str],
    readme: Path,
    config_keys: list[str] = (),
    precision: int | None = 4,
    command: str | None = None,
) -> str:
    """Markdown table: one row per run, linking to the run folder and commit."""
    base = readme.resolve().parent
    header = ["run", *config_keys, *metrics, "commit"]
    lines = [
        START,
        "<!-- Generated by exptrail. Do not edit by hand; `exptrail verify` checks these numbers. -->",
    ]
    if command:
        lines.append(f"<!-- command: {command} -->")
    lines += ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    for run in runs:
        link = Path(os.path.relpath(run.path.resolve(), base)).as_posix()
        config, summary = run.config, run.summary
        cells = [f"[{run.name}]({link}/)"]
        cells += [format_value(config.get(k), None) for k in config_keys]  # configs: exact
        cells += [format_value(summary.get(k), precision) for k in metrics]
        cells.append(commit_cell(run))
        lines.append("| " + " | ".join(cells) + " |")
    lines.append(END)
    return "\n".join(lines)


def replace_block(text: str, block: str) -> str:
    """Replace the results block in ``text`` (or append one). Idempotent."""
    starts, ends = text.count(START), text.count(END)
    if starts == 0 and ends == 0:
        sep = "" if text.endswith("\n\n") or not text else ("\n" if text.endswith("\n") else "\n\n")
        return f"{text}{sep}{block}\n"
    if starts != 1 or ends != 1 or text.index(START) > text.index(END):
        raise ValueError(f"README must contain exactly one {START} ... {END} pair")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    return head + block + tail


def write_table(readme: Path, block: str) -> bool:
    """Write the block into ``readme``. Returns True if the file changed."""
    old = readme.read_text() if readme.exists() else ""
    new = replace_block(old, block)
    if new != old:
        readme.write_text(new)
    return new != old


# -- verify ----------------------------------------------------------------

_LINK = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")
_FIXED = re.compile(r"^-?\d+\.(\d+)$")
_SCI = re.compile(r"^-?\d(?:\.(\d+))?e[+-]\d+$", re.I)


@dataclass
class VerifyResult:
    checked: int = 0
    rows: int = 0
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors and self.rows > 0


def _split_row(line: str) -> list[str]:
    cells = re.split(r"(?<!\\)\|", line.strip().strip("|"))
    return [c.strip() for c in cells]


def cell_matches(cell: str, value) -> bool:
    """Does the displayed ``cell`` agree with the saved ``value`` at the shown precision?"""
    if value is None:
        return cell == MISSING
    if isinstance(value, bool) or isinstance(value, int):
        if re.fullmatch(r"-?\d+", cell):
            return int(cell) == int(value)
        value = float(value)
    if isinstance(value, float):
        if m := _FIXED.match(cell):
            return f"{value:.{len(m.group(1))}f}" == cell
        if m := _SCI.match(cell):
            digits = len(m.group(1) or "")
            return f"{value:.{digits}e}".lower() == cell.lower()
        if re.fullmatch(r"-?\d+", cell):
            return f"{value:.0f}" == cell
        return repr(value) == cell
    return format_value(value, None) == cell


def extract_block(text: str) -> str | None:
    if START not in text or END not in text:
        return None
    return text.split(START, 1)[1].split(END, 1)[0]


def verify_readme(readme: Path, strict: bool = False) -> VerifyResult:
    """Check every number in the results block against the runs it links to."""
    res = VerifyResult()
    block = extract_block(readme.read_text())
    if block is None:
        res.errors.append(f"{readme}: no {START} ... {END} block found")
        return res
    lines = [ln for ln in block.splitlines() if ln.strip().startswith("|")]
    if len(lines) < 2:
        res.errors.append(f"{readme}: results block has no table")
        return res
    header = _split_row(lines[0])
    if header[0] != "run" or header[-1] != "commit":
        res.errors.append(f"{readme}: unexpected table header {header}")
        return res
    base = readme.resolve().parent
    for line in lines[2:]:
        cells = _split_row(line)
        res.rows += 1
        link = _LINK.search(cells[0])
        if len(cells) != len(header) or not link:
            res.errors.append(f"malformed row: {line.strip()}")
            continue
        label = link.group(1)
        path = (base / link.group(2)).resolve()
        if not is_run_dir(path):
            res.errors.append(f"{label}: run folder {link.group(2)} not found")
            continue
        run = SavedRun(path)
        config, summary = run.config, run.summary
        if run.name != label:
            res.errors.append(f"{label}: run folder is named {run.name!r}")
        for key, cell in zip(header[1:-1], cells[1:-1]):
            source, value = (summary, summary.get(key)) if key in summary else (config, config.get(key))
            res.checked += 1
            # metrics may be rounded for display; config values are shown exactly
            exact = source is config and key not in summary
            if not (cell == format_value(value, None) if exact else cell_matches(cell, value)):
                where = "summary.json" if source is summary else "config.json"
                res.errors.append(f"{label}: {key} shows {cell} but {where} has {value!r}")
        commit, shown = run.commit, cells[-1]
        if commit:
            short = re.search(r"`([0-9a-f]+)`", shown)
            linked = re.findall(r"/commit/([0-9a-f]+)", shown)
            if not short or short.group(1) != commit[:7] or any(c != commit for c in linked):
                res.errors.append(f"{label}: commit shows {shown} but meta.json has {commit[:7]}")
        elif shown != "no-git":
            res.errors.append(f"{label}: commit shows {shown} but run has no git info")
        problems = []
        if run.status != "finished":
            problems.append(f"status is {run.status}")
        if run.dirty:
            problems.append("ran on a dirty working tree")
        if not commit:
            problems.append("has no commit")
        for p in problems:
            (res.errors if strict else res.warnings).append(f"{label}: {p}")
    if res.rows == 0:
        res.errors.append(f"{readme}: results table has no rows")
    return res
